language: generic

services:
  - docker

deploy:
  - provider: elasticbeanstalk
    region: ap-south-1
    app: "my-first-app"
    env: "Myfirstapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket"

    bucket_path: "docker"

    on:
      branch: main

  - provider: elasticbeanstalk
    region: ap-south-1
    app: "test-app"
    env: "Testapp-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "my-first-app-bucket"
  
    bucket_path: "docker"

    on:
      branch: testing 